"""Modify column name in contacts table

Revision ID: 0bd714da1dd9
Revises: 2046f0af6432
Create Date: 2023-11-28 12:47:13.237505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd714da1dd9'
down_revision: Union[str, None] = '2046f0af6432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('contacts', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('contacts', 'Phone')
    op.drop_column('contacts', 'Designation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('Designation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('Phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'designation')
    # ### end Alembic commands ###
