"""modify column in 'addresses' table

Revision ID: 2b855fe941d0
Revises: 79c17856218b
Create Date: 2023-12-13 15:11:38.679966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b855fe941d0'
down_revision: Union[str, None] = '79c17856218b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('extra_info', sa.String(), nullable=True))
    op.drop_column('addresses', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'extra_info')
    # ### end Alembic commands ###
