"""Add cascade='all, delete-orphan' in contacts relationship in Services table

Revision ID: 33ca9555329d
Revises: 34349cc06724
Create Date: 2024-06-04 15:16:54.463549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ca9555329d'
down_revision: Union[str, None] = '34349cc06724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
