"""Add email column in contacts table and modify some column properties

Revision ID: 4bad285ca631
Revises: a9a5d64fd731
Create Date: 2024-06-04 12:52:54.104261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bad285ca631'
down_revision: Union[str, None] = 'a9a5d64fd731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('contacts', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contacts', 'phone1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'phone1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('contacts', 'email')
    # ### end Alembic commands ###
