"""add columns in clients table

Revision ID: 75fadd131d91
Revises: 
Create Date: 2024-08-21 12:21:16.509090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fadd131d91'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('ccare_account_manager_id', sa.Integer(), nullable=False))
    op.add_column('clients', sa.Column('sales_account_manager_id', sa.Integer(), nullable=False))
    op.create_foreign_key('clients_ccare_account_manager_id_fkey', 'clients', 'contacts', ['sales_account_manager_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('clients_sales_account_manager_id_fkey', 'clients', 'contacts', ['ccare_account_manager_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_ccare_account_manager_id_fkey', 'clients', type_='foreignkey')
    op.drop_constraint('clients_sales_account_manager_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'sales_account_manager_id')
    op.drop_column('clients', 'ccare_account_manager_id')
    # ### end Alembic commands ###
