"""add table 'service_types'

Revision ID: 79c17856218b
Revises: 811d8c968c35
Create Date: 2023-12-13 12:47:14.853730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c17856218b'
down_revision: Union[str, None] = '811d8c968c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('services', sa.Column('service_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'service_types', ['service_type_id'], ['id'])
    op.drop_column('services', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'service_type_id')
    op.drop_table('service_types')
    # ### end Alembic commands ###
