"""correct relationship parameters in 'leased_links' table

Revision ID: 811d8c968c35
Revises: fc4665ac977f
Create Date: 2023-12-11 15:30:15.281245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811d8c968c35'
down_revision: Union[str, None] = 'fc4665ac977f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
