"""Add ondelete='CASCADE' in service_id foreign key relationship in Contacts table

Revision ID: 88747c355f07
Revises: 33ca9555329d
Create Date: 2024-06-04 15:29:03.199673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88747c355f07'
down_revision: Union[str, None] = '33ca9555329d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_service_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_service_id_fkey', 'contacts', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###
