"""Add ondelete='CASCADE' in client_id and vendor_id foreign key relationship in Addresses table

Revision ID: 997dc279e3ab
Revises: a805bc7a72b8
Create Date: 2024-06-10 11:20:11.386008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997dc279e3ab'
down_revision: Union[str, None] = 'a805bc7a72b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_client_id_fkey', 'addresses', type_='foreignkey')
    op.drop_constraint('addresses_service_id_fkey', 'addresses', type_='foreignkey')
    op.drop_constraint('addresses_vendor_id_fkey', 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'addresses', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'addresses', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key('addresses_vendor_id_fkey', 'addresses', 'vendors', ['vendor_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('addresses_service_id_fkey', 'addresses', 'services', ['service_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('addresses_client_id_fkey', 'addresses', 'clients', ['client_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
