"""Add ondelete='CASCADE' in client_id and vendor_id foreign key relationship in Contacts table

Revision ID: a805bc7a72b8
Revises: 88747c355f07
Create Date: 2024-06-04 15:40:05.444197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a805bc7a72b8'
down_revision: Union[str, None] = '88747c355f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_client_id_fkey', 'contacts', type_='foreignkey')
    op.drop_constraint('contacts_vendor_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contacts', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_vendor_id_fkey', 'contacts', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key('contacts_client_id_fkey', 'contacts', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
