"""Add on delete restriction in Pops table owner_id column

Revision ID: a9a5d64fd731
Revises: afb10e1a3d8b
Create Date: 2024-05-16 15:08:22.989379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a5d64fd731'
down_revision: Union[str, None] = 'afb10e1a3d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pops_owner_fkey', 'pops', type_='foreignkey')
    op.create_foreign_key(None, 'pops', 'vendors', ['owner'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pops', type_='foreignkey')
    op.create_foreign_key('pops_owner_fkey', 'pops', 'vendors', ['owner'], ['id'])
    # ### end Alembic commands ###
