"""add column and modify column properties in 'addresses' table

Revision ID: c47f810550f6
Revises: 2b855fe941d0
Create Date: 2023-12-14 10:34:48.197035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47f810550f6'
down_revision: Union[str, None] = '2b855fe941d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('area', sa.String(), nullable=False))
    op.alter_column('addresses', 'holding',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'thana',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'thana',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'holding',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('addresses', 'area')
    # ### end Alembic commands ###
