"""Add column 'client_types_id' in 'clients' table

Revision ID: e16173703a20
Revises: 18ffe2b2074b
Create Date: 2023-11-23 15:44:03.560010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16173703a20'
down_revision: Union[str, None] = '18ffe2b2074b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'client_types', ['client_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'client_type_id')
    # ### end Alembic commands ###
