"""add constraint not null to client_id, location and type column

Revision ID: e6133c6c3f43
Revises: f444fa31ac60
Create Date: 2023-12-11 10:32:50.539920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6133c6c3f43'
down_revision: Union[str, None] = 'f444fa31ac60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('service', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('service', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('service', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('service', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
