"""drop tables 'backbones' & 'lastmiles' and created 'leased_links

Revision ID: fc4665ac977f
Revises: c5ff2d7d43f8
Create Date: 2023-12-11 15:26:20.072327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4665ac977f'
down_revision: Union[str, None] = 'c5ff2d7d43f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leased_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('link_from', sa.String(), nullable=False),
    sa.Column('link_to', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lastmiles')
    op.drop_table('backbones')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backbones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_from', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_to', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='backbones_service_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='backbones_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='backbones_pkey')
    )
    op.create_table('lastmiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_from', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('link_to', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='lastmiles_service_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='lastmiles_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='lastmiles_pkey')
    )
    op.drop_table('leased_links')
    # ### end Alembic commands ###
